name: Update site
on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *" # Every day at 2am. Modify this as you see fit

jobs:
  DeploySite:
    runs-on: ubuntu-latest
    steps:
      - name: Data Format Converter Action
        uses: fabasoad/data-format-converter-action@v0.2.3
        id: xml2json
        token: ${{ secrets.METRICS_TOKEN }}
        with:
          input: "content/utils/feed.xml.njk"
          from: "xml"
          to: "json"
      - name: Deploy site
        uses: lwojcik/github-action-deploy-static-site@v1
        with:
          platform: netlify
          netlify_deploy_hook_url: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
          always_deploy: true
          # Using Netlify? Configure this action as follows:
          # platform: netlify
          # netlify_deploy_hook_url: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
          # always_deploy: true
